apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-files-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud-local
  hostPath:
    path: /mnt/tank/nextcloud/files
    type: DirectoryOrCreate
