apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-files
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nextcloud-local
  resources:
    requests:
      storage: 1Ti
