apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  volumeName: vaultwarden-pv
